import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml",
    "~/.config/alacritty/keybindings.toml",
]

[font]
size = 13.0

[font.normal]
family = "JetBrainsMono NerdFont"
style = "Regular"
